### ISSUE TITLE
Vuex integration: actions are not being called

### ISSUE THREAD

**Issue by Conson1** [MetinSeylan/Vue-Socket.io#117] opened 2018-01-30 13:53 UTC
I used the Vuex integration in many other projects and works just fine. Now i'm starting a new project and trying to use it, but the actions are never called. The "SOCKET_" prefix in the mutations works fine but the "socket_" prefix used in actions doesn't work.

export default new Vuex.Store({
    state: {
        connect: false,
        message: null
    },
    mutations:{
        SOCKET_CONNECT: (state,  status ) => {
            //work fine...
        },
        SOCKET_USER_MESSAGE: (state,  message) => {
            console.log('mutation called');
        }
    },
    actions: {
        otherAction: (context, type) => {
            return true;
        },
        socket_userMessage: (context, message) => {
            //this actions are never called
            console.log('action called');
        }
    }
})

**Comment by talberkoSB** [comment] 2018-01-31 18:15
for me also

**Comment by GsiorX** [comment] 2018-02-01 14:56
Yeah, same here. I have found out that the issue is caused by the latest release. For now use the version 2.1.1-a not the latest "b" version. [https://stackoverflow.com/a/15892076](url)

**Comment by chambber** [comment] 2018-02-02 01:35
I was debugging and discovered the following:

https://github.com/MetinSeylan/Vue-Socket.io/blob/895166790387d69f1bc986f58793550e76b1f761/src/Observer.js#L27

If you put this code in the mounted() for example:
```javascript
    this.$socket.onevent = (packet) => {
      console.log(packet); //eslint-disable-line
    };
```

It shows that `packet.data[0]` is literally what comes from `io.emit('new message', message)`, literally **new message**.
Then mutation must be `SOCKET_new message` or `SOCKET_NEW MESSAGE`.
I changed the mutation and it worked again!

**Comment by wenpoqiu** [comment] 2018-02-02 16:53
in file Observer.js,  this code
`let camelcased = 'socket_'+**event.toLowerCase()
                    .replace('SOCKET_', '')**
                    .replace(/[\W\s_]+(\w)/g, (match, p1) => p1.toUpperCase())`
has a bug, the correct code is:
`let camelcased = 'socket_'+**event.replace('SOCKET_', '')
                    .toLowerCase()**
                    .replace(/[\W\s_]+(\w)/g, (match, p1) => p1.toUpperCase())`
the sequence is wrong.

**Comment by probil** [comment] 2018-03-30 09:34
Can be fixed by this PR
https://github.com/MetinSeylan/Vue-Socket.io/pull/118

**Comment by alancwoo** [comment] 2018-04-21 19:49
I'm not sure if it's a misunderstanding my part, if the socket server emits an event, for example `io.emit('newMessage', message)`, is the store supposed to call the action `socket_newMessage`?

I'm able to call the action in a component itself within the `sockets` object, but not in the store directly. 
Or am I misunderstanding something?

**Closed** 2018-07-23 09:55 UTC

**Comment by joshporter1** [comment] 2018-10-22 20:36
Is this actually resolved? I am still having this issue with action-based listeners not being registered.

**Comment by probil** [comment] 2018-10-22 20:56
@joshporter1 Try [this ](https://github.com/probil/vue-socket.io-extended) instead

**Comment by joshporter1** [comment] 2018-10-22 22:56
@probil thanks, I'll try that. Is this repo no longer maintained?
